### PR TITLE
Fix/local mira

### PR DESCRIPTION
**Pull request by mikegwhit**
References https://github.com/nearform/mira/issues/88

Solves by way of utilizing `--preserve-symlinks` and then modifies `getCDKArgs` to supply a file that is not symlinked.  This file is created programmatically (which may introduce conflicts later on should a package called `mira-bootstrap` ever be created).  This file is a one-line code file requiring the intended Mira target file for all CDK applications: `dist/src/cdk/app.js`

This functionality of `--preserve-symlinks` seems like it was introduced in Node v6.  It's unknown if a later version of Node or CDK will break this functionality.

### CODE REVIEW

**Review by irelandm — COMMENTED** [review]
Once this is checked to be working for everyone, please add a doc file that explains how and when to use it

**Review by irelandm — COMMENTED** [review]
I'm getting this error now (wasn't in a previous version of this PR):

>>>
marki@Marks-MBP-2:~/mira/mira (git fix/rebuild-dist)  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - [10:23:22]
$ node scripts/link.js ../test8-s3wh/
Looks like Mira has already been installed in mira-sample-s3-webhosting
Backing up old mira dependency to /Users/marki/mira/test8-s3wh/mira.old
mira.old folder already exists, deleting.
internal/fs/utils.js:269
    throw err;
    ^

Error: EEXIST: file already exists, symlink '/Users/marki/mira/mira/scripts/bin/mira' -> '/Users/marki/mira/test8-s3wh/node_modules/.bin/mira'
    at Object.symlinkSync (fs.js:1095:3)
    at /Users/marki/mira/mira/scripts/link.js:24:12
    at Array.forEach (<anonymous>)
    at createMiraBootstrap (/Users/marki/mira/mira/scripts/link.js:23:40)
    at Object.<anonymous> (/Users/marki/mira/mira/scripts/link.js:140:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -17,
  syscall: 'symlink',
  code: 'EEXIST',
  path: '/Users/marki/mira/mira/scripts/bin/mira',
  dest: '/Users/marki/mira/test8-s3wh/node_modules/.bin/mira'
}

**Comment by nigelhanlon** [comment]
> marki@Marks-MBP-2:~/mira/mira (git fix/rebuild-dist)

Would the branch you are on have something to do with the symlink issue? On the `fix/mira-local` branch it appears to be working without issue.

**Comment by mikegwhit** [comment]
Patched @irelandm @nigelhanlon

**Comment by nigelhanlon** [comment]
This works for me. I am happy to approve but will hold off until Mark has a chance to test as well.

**Review by irelandm — APPROVED** [review]
This works for me now.

At some point we should change those NOOP comments to log messages (we'd like to know if they are ever reached), but good to go

**Pull request merged**
