### PR TITLE
Changed the NodeJS Version

### PR DESCRIPTION
**Pull request by CledersonE**
Changed the nodeJS version to test the project

### CODE REVIEW

**Comment by irelandm** [comment]
Thanks Clederson. There's a prompt that we'll need to drop the 10.x build from the CI.

**Comment by simoneb** [comment]
Please:

- remove Node 10 from the CI workflow
- find a way to list all the necessary dependencies without having to hardcode them in the source code (and fix the docs which are wrong as they only list a subset of the dependencies)
- update all the lambdas to Node 12

**Comment by irelandm** [comment]
A quick note on the dependencies list - this issue will 'go away' when we move to CDK v2, as there will be far fewer dependencies.

**Comment by simoneb** [comment]
> A quick note on the dependencies list - this issue will 'go away' when we move to CDK v2, as there will be far fewer dependencies.

@irelandm do you think there is a way to automate this? What we noticed is that the list of deps is hardcoded in the docs and in the source code, and they're both different and wrong. If there was a way to "ask" cdk for what the dependencies are, we would solve this problem once and for all as we won't have to hardcode them anymore.

**Comment by irelandm** [comment]
> > A quick note on the dependencies list - this issue will 'go away' when we move to CDK v2, as there will be far fewer dependencies.
> 
> @irelandm do you think there is a way to automate this? What we noticed is that the list of deps is hardcoded in the docs and in the source code, and they're both different and wrong. If there was a way to "ask" cdk for what the dependencies are, we would solve this problem once and for all as we won't have to hardcode them anymore.

Yes, there are way too many dependencies listed in both docs and package.json. I think the 'peerdependencies' should be the source of truth here and we should just refer to that in the docs.

I don't know how to automate the creation of that list though, beyond following the steps of making a new project.

But CDK v2 is in release candidate right now an dependencies will be much reduced, e.g.:
```
  "dependencies": {
    "@aws-cdk/assert": "2.0.0-rc.1",
    "aws-cdk-lib": "2.0.0-rc.1",
    "constructs": "10.0.5"
  }
```

So automating this right now would be a waste of effort.

**Comment by irelandm** [comment]
For now though, we'll also need to update the dependencies listed in https://github.com/nearform/mira/blob/master/scripts/postinstall.js

**Comment by CledersonE** [comment]
Updated changes:
- Removed Node 10 from the CI workflow;
- Fixed the list of dependencies for the "Start New Project" Quickstart;

I've changed the nodeJS version to 12 in all of the files that contains the runtime section (the files in this search: https://github.com/nearform/mira/search?q=NODEJS),  but one lambda function still is using the nodeJS10 version.

**Pull request closed without merging**
